on: [ pull_request ]

name: Test Cache Disabled

jobs:
  test-devstack-swift:
    runs-on: ubuntu-latest
    name: Test Devstack Swift Service
    steps:
      - uses: actions/checkout@v3

      - id: devstack
        name: Run Devstack Swift Action
        uses: ./
        with:
          use-cache: "false"

      - name: Import Openstack Credentials
        run: echo "${{ steps.devstack.outputs.credentials }}" > openrc

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Openstack Client
        run: pip3 install python-openstackclient

      - name: Openstack Object Storage Functionality Test
        run: |
          cat openrc
          . openrc
          openstack container create default
          echo hello > greading
          openstack object create default greading
          rm greading
          openstack object save default greading
          grep -Fxq hello greading
