on: [push, pull_request]

name: Test (s3api)

concurrency: test-s3api

jobs:
  run-test-cache-miss:
    needs: delete-cache
    name: Cache Miss
    uses: ./.github/workflows/test-s3api.yaml
    with:
      ${{ github.sha }}-s3api

  run-test-cache-hit:
    needs: run-test-cache-miss
    name: Cache Hit
    uses: ./.github/workflows/test-s3api.yaml
    with:
      ${{ github.sha }}-s3api
